"""Identity protocol (Phase 9).

Responsibility split, frozen:
- learner_id: generated by Firefly exactly once, persisted long-term.
- course_id / resource_id: generated by the Resource Manager.
- session_id / pipeline_id / curriculum_id: generated by teach-mcp. Neither
  Firefly nor Z Code nor the model may ever mint one.
"""

from __future__ import annotations

import re
import secrets

_LEARNER_ID_RE = re.compile(r"^ff-[0-9a-f]{8}$")


class IdentityError(Exception):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


def new_learner_id() -> str:
    return "ff-" + secrets.token_hex(4)


def is_valid_learner_id(learner_id: str) -> bool:
    return bool(_LEARNER_ID_RE.match(learner_id or ""))


def ensure_learner_id(settings) -> str:
    """Return the stable learner_id, creating and persisting it once.

    ``settings`` is a core.settings_manager.SettingsManager (or any object
    with learning_learner_id / set_learning_learner_id).
    """
    current = (settings.learning_learner_id or "").strip()
    if current:
        if not is_valid_learner_id(current):
            raise IdentityError(
                "LEARNER_ID_CORRUPT",
                f"已保存的 learner_id 形态非法，拒绝静默重置: {current!r}",
            )
        return current
    learner_id = new_learner_id()
    settings.set_learning_learner_id(learner_id)
    return learner_id
